services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\Breadcrumb\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    OSW3\Breadcrumb\Service\BreadcrumbService:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController' }